-- [[ UI ]]
vim.api.nvim_set_hl(0, 'Normal', { bg = "NONE"})
vim.api.nvim_set_hl(0, 'NormalFloat', { ctermfg = 8, ctermbg = 0 })
vim.api.nvim_set_hl(0, 'Pmenu', { ctermfg = 8, ctermbg = 0 })
vim.api.nvim_set_hl(0, 'PmenuSel', { ctermfg = 16, ctermbg = 8, underline = false })
vim.api.nvim_set_hl(0, 'PmenuThumb', { ctermbg = 8 })
vim.api.nvim_set_hl(0, 'LineNrAbove', { ctermfg = 8 })
vim.api.nvim_set_hl(0, 'LineNr', { ctermfg = 8, bold = true })
vim.api.nvim_set_hl(0, 'LineNrBelow', { ctermfg = 8 })
vim.api.nvim_set_hl(0, 'EndOfBuffer', { ctermfg = 8 })

-- [[ Signs ]]
vim.api.nvim_set_hl(0, "DiagnosticHint", { ctermfg = 6 })
vim.api.nvim_set_hl(0, "DiagnosticInfo", { ctermfg = 4 })
vim.api.nvim_set_hl(0, "DiagnosticWarn", { ctermfg = 3 })
vim.api.nvim_set_hl(0, "DiagnosticError", { ctermfg = 1 })
vim.api.nvim_set_hl(0, "GitSignsStagedAdd", { link = "GitSignsAdd" })
vim.api.nvim_set_hl(0, "GitSignsStagedChange", { link = "GitSignsChange" })
vim.api.nvim_set_hl(0, "GitSignsStagedDelete", { link = "GitSignsDelete" })

-- [[ Highlighting ]]
vim.api.nvim_set_hl(0, '@type.builtin', { ctermfg = 3 })
vim.api.nvim_set_hl(0, '@comment', { link = "Comment" })
vim.api.nvim_set_hl(0, '@variable', { ctermfg = 12 })
vim.api.nvim_set_hl(0, '@keyword', { ctermfg = 9 })
vim.api.nvim_set_hl(0, '@boolean', { ctermfg = 13 })
vim.api.nvim_set_hl(0, '@number', { ctermfg = 13 })
vim.api.nvim_set_hl(0, '@string', { ctermfg = 10 })
vim.api.nvim_set_hl(0, '@punctuation', { ctermfg = 11 })
vim.api.nvim_set_hl(0, '@constructor', { ctermfg = 11 })
vim.api.nvim_set_hl(0, '@function', { ctermfg = 10 })
vim.api.nvim_set_hl(0, '@function.call', { ctermfg = 10 })
vim.api.nvim_set_hl(0, '@operator', { ctermfg = 11 })
vim.api.nvim_set_hl(0, 'Comment', { ctermfg = 8, italic = true })
vim.api.nvim_set_hl(0, 'Type', { ctermfg = 3 })
vim.api.nvim_set_hl(0, 'Statement', { ctermfg = 9 })
vim.api.nvim_set_hl(0, "Conceal", { link = "Special" })
vim.api.nvim_set_hl(0, "PreProc", { ctermfg = 14 })
