export PATH="/usr/local/sbin:/usr/sbin:/sbin:$PATH"
export EDITOR=nvim
export TERMINAL=alacritty
export QT_QPA_PLATFORMTHEME="qt6ct"
export SAL_USE_VCLPLUGIN="qt6"
export KEYTIMEOUT=1
export PYTHONPATH="/home/elliot/OneDrive/Programming/CipherChallenge"
export VIRTUAL_ENV_DISABLE_PROMPT=1
export MANPAGER="nvim +Man!"
export DIFFPROG="nvim -d"
