#!/bin/sh

export XAUTHORITY=/home/elliot/.Xauthority
export DISPLAY=:0
export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus"

dunstify "Disconnected from AC" -u low -i battery-good
rm /tmp/batteryfull
