#!/usr/bin/env sh

# ====== Command/Application bindings =======
riverctl map normal Super Space spawn "footclient"
riverctl map normal Super+Control Space spawn "foot"
riverctl map normal Super+Shift Space spawn "fuzzel --no-icons"
riverctl map normal Super+Shift Q spawn "power-options"
riverctl map normal Super B spawn "firefox"
riverctl map normal Super+Shift B spawn "librewolf -P alt"
riverctl map normal Super G spawn "pidof -q gammastep && pkill gammastep || gammastep -O 4000"
riverctl map normal Super E spawn "footclient yazi"
riverctl map normal Super W spawn "footclient nvim todo"
riverctl map normal Super S spawn "~/.config/river/init"

riverctl map normal Super P	spawn "screenshot"			# screenshot selection
riverctl map normal Super+Shift P spawn "screenshot -f" # screenshot whole screen

# ====== Window bindings ======
riverctl map normal Super Q close
riverctl map normal Super F toggle-fullscreen

riverctl map normal Super N focus-view next
riverctl map normal Super E focus-view previous
riverctl map normal Super+Shift N swap next
riverctl map normal Super+Shift E swap previous
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

riverctl map normal Super Return focus-output left
riverctl map normal Super Backspace focus-output right
riverctl map normal Super+Shift Return send-to-output left
riverctl map normal Super+Shift Backspace send-to-output right

riverctl map normal Super Z zoom

riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"
riverctl map normal Super M send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super I send-layout-cmd rivertile "main-ratio +0.05"
riverctl map normal Super Minus send-layout-cmd rivertile "main-count -1"
riverctl map normal Super Plus send-layout-cmd rivertile "main-count +1"

# ====== Floating bindings =======
riverctl map normal Super T toggle-float

# Move floating windows
riverctl map normal Super Left move left 100
riverctl map normal Super Down move down 100
riverctl map normal Super Up move up 100
riverctl map normal Super Right move right 100
riverctl map-pointer normal Super BTN_LEFT move-view
# Resize floating windows
riverctl map normal Super+Shift Left resize horizontal -100
riverctl map normal Super+Shift Down resize vertical -100
riverctl map normal Super+Shift Up resize vertical 100
riverctl map normal Super+Shift Right resize horizontal 100
riverctl map-pointer normal Super BTN_RIGHT resize-view

# === Tag keybinds ===
for i in $(seq 1 9)
do
	tag=$((1 << ($i - 1)))

	riverctl map normal Super $i set-focused-tags $tag
	riverctl map normal Super+Shift $i set-view-tags $tag
	riverctl map normal Super+Control $i toggle-focused-tags $tag
	riverctl map normal Super+Shift+Control $i toggle-view-tags $tag
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map -repeat $mode None XF86AudioRaiseVolume  spawn 'volume up'
    riverctl map -repeat $mode None XF86AudioLowerVolume  spawn 'volume down'
    riverctl map $mode None XF86AudioMute spawn 'volume mute'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map -repeat $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +10%'
    riverctl map -repeat $mode None XF86MonBrightnessDown spawn 'brightnessctl set 10%-'
done

riverctl declare-mode passthrough
riverctl map normal Super F11 enter-mode passthrough
riverctl map passthrough Super F11 enter-mode normal
