#!/usr/bin/env sh

# ====== Autostart =======
pidof -q waybar || riverctl spawn waybar
pidof -q kanshi || riverctl spawn kanshi # Manage outputs dynamically

riverctl spawn "foot --server"
riverctl spawn /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# ====== Keybinds =======
source "$XDG_CONFIG_HOME/river/binds"

# ====== Inputs ======
riverctl focus-follows-cursor normal
riverctl set-cursor-warp on-focus-change
riverctl hide-cursor when-typing enabled
riverctl input pointer-1739-52876-VEN_06CB:00_06CB:CE8C_Touchpad natural-scroll enabled
riverctl input pointer-1739-52876-VEN_06CB:00_06CB:CE8C_Touchpad tap enabled
riverctl input pointer-1739-52876-VEN_06CB:00_06CB:CE8C_Touchpad pointer-accel 0.7
riverctl input pointer-1739-52876-VEN_06CB:00_06CB:CE8C_Touchpad accel-profile adaptive

riverctl keyboard-layout gb

riverctl set-repeat 50 300 # Set keyboard repeat rate

# ======= Outputs =======
# Set background image
swaybg -m fill -i ~/pictures/carnotaurus.jpg &

# Configure borders
riverctl border-color-focused 0x98971A
riverctl border-color-unfocused 0x666666
riverctl border-width 1

# ======== Rules =========
# Make all views with an app-id that starts with "float" and title "foo" start floating.
# riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
# riverctl rule-add -app-id "bar" csd

# Make all windows use server-side decorations
riverctl rule-add -title "*" ssd

# Rules for popup filepicker (from xdg-desktop-portal-termfilechooser)
riverctl rule-add -title "filepicker" float
riverctl rule-add -title "filepicker" dimensions 1250 750

# riverctl rule-add -title 'LocalSend' float
# riverctl rule-add -title 'LocalSend' position 0 0

# ======== Layout =========
# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 0 -outer-padding 0 -main-ratio 0.55 &

systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river
systemctl --user restart xdg-desktop-portal
