#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.

# Autostart
if !(pidof -q waybar); then
	riverctl spawn waybar
fi

# ====== Application bindings =======
riverctl map normal Super+Shift Escape spawn alacritty
riverctl map normal Super Escape spawn foot
riverctl map normal Super B spawn librewolf

# ====== Window bindings ======
riverctl map normal Super Q close
riverctl map normal Super Z toggle-fullscreen
riverctl map normal Super+Shift E exit

riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

riverctl map normal Super Space focus-output next
riverctl map normal Super+Shift Space send-to-output next

riverctl map normal Super Return zoom

riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# Move floating windows
riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100
riverctl map-pointer normal Super BTN_LEFT move-view
# Snap floating windows to edges
riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right
# Resize floating windows
riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100
riverctl map-pointer normal Super BTN_RIGHT resize-view

riverctl map-pointer normal Super BTN_MIDDLE toggle-float
riverctl map normal Super T toggle-float


# ====== Tags =======
for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags


# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
# riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
# riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
# riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume  spawn '~/.local/bin/volume up'
    riverctl map $mode None XF86AudioLowerVolume  spawn '~/.local/bin/volume down'
    riverctl map $mode None XF86AudioMute         spawn '~/.local/bin/volume muted'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +10%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 10%-'
done

# ====== Inputs ======
riverctl focus-follows-cursor normal
riverctl set-cursor-warp on-focus-change
riverctl input pointer-1739-52876-VEN_06CB:00_06CB:CE8C_Touchpad natural-scroll enabled
riverctl input pointer-1739-52876-VEN_06CB:00_06CB:CE8C_Touchpad tap enabled
riverctl input pointer-1739-52876-VEN_06CB:00_06CB:CE8C_Touchpad pointer-accel 0.7

riverctl keyboard-layout gb

riverctl set-repeat 50 300 # Set keyboard repeat rate

# ======= Outputs =======
# Set background and border color
# riverctl background-color 0x404040
wlr-randr --output DP-1 --pos 0,-1080

swww-daemon &
swww img ~/pictures/wallpapers/carnotaurus.jpg

riverctl border-color-focused 0x983e55
riverctl border-color-unfocused 0x666666
riverctl border-width 2


# ======== Rules =========
# Make all views with an app-id that starts with "float" and title "foo" start floating.
# riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
# riverctl rule-add -app-id "bar" csd

# Always spawn browser on tag 1
riverctl rule-add -title "LibreWolf" tags 000000001

# ======== Layout =========
# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 8 -outer-padding 8 &
