#!/usr/bin/env sh

# ====== Autostart =======
if !(pidof -q waybar); then
	riverctl spawn waybar
fi

riverctl spawn "foot --server"

# Manage outputs dynamically
if !(pidof -q kanshi); then
	riverctl spawn kanshi
fi

riverctl spawn LibreWolf

# ====== Application bindings =======
riverctl map normal Super Escape spawn "footclient tmux"
riverctl map normal Super+Shift Escape spawn foot
riverctl map normal Super Return spawn fuzzel
riverctl map normal Super B spawn librewolf
riverctl map normal Super N spawn "if !(pidof -q gammastep); then gammastep -O 4500; else pkill gammastep; fi"
riverctl map normal Super E spawn dolphin
riverctl map normal Super W spawn "footclient nvim todo"

# ====== Window bindings ======
riverctl map normal Super Q close
riverctl map normal Super F toggle-fullscreen

riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

riverctl map normal Super Space focus-output next
riverctl map normal Super+Shift Space send-to-output next

riverctl map normal Super Z zoom

riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count -1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count +1"

# ====== Floating mode =======
riverctl declare-mode float
riverctl map normal Super R enter-mode float
riverctl map float Super R enter-mode normal
riverctl map float None Escape enter-mode normal

riverctl map-pointer float Super BTN_MIDDLE toggle-float
riverctl map float Super T toggle-float
riverctl map normal Super T toggle-float

# Move floating windows
riverctl map float Super H move left 100
riverctl map float Super J move down 100
riverctl map float Super K move up 100
riverctl map float Super L move right 100
riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer float Super BTN_LEFT move-view
# Resize floating windows
riverctl map float None H resize horizontal -100
riverctl map float None J resize vertical 100
riverctl map float None K resize vertical -100
riverctl map float None L resize horizontal 100
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer float Super BTN_RIGHT resize-view
# Snap floating windows to edges
riverctl map float Super+Shift H snap left
riverctl map float Super+Shift J snap down
riverctl map float Super+Shift K snap up
riverctl map float Super+Shift L snap right


# ====== Tags =======
for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags


# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super+Alt K send-layout-cmd rivertile "main-location top"
riverctl map normal Super+Alt L send-layout-cmd rivertile "main-location right"
riverctl map normal Super+Alt J send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super+Alt H send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This is useful for using virtual machines
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map -repeat $mode None XF86AudioRaiseVolume  spawn '~/.local/bin/volume up'
    riverctl map -repeat $mode None XF86AudioLowerVolume  spawn '~/.local/bin/volume down'
    riverctl map $mode None XF86AudioMute         spawn '~/.local/bin/volume muted'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with brightnessctl (https://github.com/Hummer12007/brightnessctl)
    riverctl map -repeat $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +10%'
    riverctl map -repeat $mode None XF86MonBrightnessDown spawn 'brightnessctl set 10%-'
done

# ====== Inputs ======
riverctl focus-follows-cursor normal
riverctl set-cursor-warp on-focus-change
riverctl input pointer-1739-52876-VEN_06CB:00_06CB:CE8C_Touchpad natural-scroll enabled
riverctl input pointer-1739-52876-VEN_06CB:00_06CB:CE8C_Touchpad tap enabled
riverctl input pointer-1739-52876-VEN_06CB:00_06CB:CE8C_Touchpad pointer-accel 0.7

riverctl keyboard-layout gb

riverctl set-repeat 50 300 # Set keyboard repeat rate

# ======= Outputs =======
# Set background image
swaybg -i ~/pictures/wallpapers/carnotaurus.jpg &

# Configure borders
riverctl border-color-focused 0x983e55
riverctl border-color-unfocused 0x666666
riverctl border-width 2

# ======== Rules =========
# Make all views with an app-id that starts with "float" and title "foo" start floating.
# riverctl rule-add -app-id 'float*' -title 'foo' float

# Make all views with app-id "bar" and any title use client-side decorations
# riverctl rule-add -app-id "bar" csd

# ======== Layout =========
# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 8 -outer-padding 8 -main-ratio 0.55 &
