[env]
term = "xterm-256color"

[window]
opacity = 0.75
# opacity = 1

[colors.normal]
black = "#232627"
red = "#942024"
green = "#11d116"
yellow = "#f67400"
blue = "#1d99f3"
magenta = "#9b59b6"
cyan = "#1abc9c"
white = "#fcfcfc"

[colors.primary]
background = "#0a0f14"
# background = "#202020"

[font]
size = 9

[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Regular"

[font.bold]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold Italic"
