import = [
    "~/.config/alacritty/tokyo-night.toml"
]

[env]
term = "xterm-256color"

[window]
opacity = 0.75
# opacity = 1

[colors.normal]
black = "#232627"
red = "#942024"
green = "#1abc9c"
yellow = "#ea9d34"
blue = "#1793d1"
magenta = "#9b59b6"
cyan = "#3e8fb0"
white = "#fcfcfc"

[colors.primary]
# background = "#0f0f17"
background = "#08080c"
foreground = "#fcfcfc"
# # background = "#202020"

[font]
size = 15

[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Regular"

[font.bold]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold Italic"
