general.import = [
    "~/.config/alacritty/gruvbox_dark.toml"
]

[env]
term = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 15

[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Regular"

[font.bold]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold"

[font.italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold Italic"
