[colors.normal]
black = "#121524"
red = "#BD2E1C"
white = "#CFE5F2"
yellow = "#FCD946"
blue = "#077BC0"
cyan = "#27B8A9"
magenta = "#A02EA4"
green = "#00D100"

[colors.primary]
background = "#101010"
foreground = "#dddddd"
