[window]
opacity = 0.85

[colors.primary]
background = '#101010'
foreground = '#ebdbc2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#73a3b7'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#ebdbd8'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'
