#!/usr/bin/sh


if [ $(echo "$1" | grep -E "^[a-z\-]+$") ]; then
	results=$(curl -s "https://aur.archlinux.org/rpc/v5/info?arg%5B%5D=$1" | jq ".resultcount")
	if [ $results = 1 ]; then
		git clone "https://aur.archlinux.org/$1.git"
	else
		echo "Package does not exist" 1>&2
	fi
else
	echo "Invalid repo name: $1" 1>&2
fi
