#!/usr/bin/sh

choice=$(echo "Power-off
Reboot
Suspend
Hibernate
Logout
Lock
UEFI Firmware
" | fuzzel --dmenu)

case "$choice" in
	'Power-off')
		systemctl poweroff
		;;
	'Reboot')
		systemctl reboot
		;;
	'Hibernate')
		systemctl hibernate
		;;
	'Suspend')
		systemctl suspend
		;;
	'Logout')
		loginctl terminate-session ''
		;;
	'Lock')
		hyprlock
		;;
	'UEFI Firmware')
		systemctl reboot --firmware-setup
		;;
esac
